### ISSUE TITLE
Feature request: Dealing with Count Data

### ISSUE THREAD

**Issue by Irazall** [borusyak/did_imputation#13]
If I understand it correctly, the package uses OLS. This is fine when dealing with continuous data. In my case, I have count data. As I don't want to log-transform the data, I would rather use Poisson or Quasi-Poisson Regression instead of OLS. Is it possible to implement this feature?

**Comment by borusyak** [comment]
Dear Chris-Gabriel,
PPML is not straightforwardly combined with the imputation method but I recommend you take a look at a great paper by Jeff Wooldridge on robust DiD estimation with Poisson.

Kirill
