### ISSUE TITLE
Feature request Event_plot: Allow more flexible naming conventions in stub_lag() and stub_lead() to plot contemporary effect from "wooldid" command

### ISSUE THREAD

**Issue by Mbjoerkh** [borusyak/did_imputation#14]
Hi, 

I'm having trouble plotting the baseperiod of estimates from the new "wooldid" command. I've posted an issue with them and am crossposting it here as well: https://github.com/thegland/wooldid/issues/2#issue-2121434308 . 

I am not able to include the first post-treatment period when attempting to plot the results from wooldid,  because that command names the contemporary effect (ES_att_contemp) instead of "ES_att_post0". 

![image](https://github.com/borusyak/did_imputation/assets/33209918/c04dad9d-7002-48df-ab16-140b4fc99765)

I realize this is as much an issue for the wooldid command as it is for event_plot, but would it be possible to make the stub_lag() and stub_lead() options more flexible, or some other option to include contemporary effects and/or base periods that have been named differently?

I would have thought it would be relatively easy to rename the matrix element but I've tried quite a few approaches without being able to do it, so adding example code for how to do that would be another option.

`wooldid Y i t ttre, espre(10) espost(21)

try plotting with event_plot
event_plot , stub_lag(ES_att_post#) stub_lead(ES_att_pre#)`

**Comment by Mbjoerkh** [comment]
The wooldid command has been updated so that the naming conventions are compatible with event_plot (https://github.com/thegland/wooldid/issues/2).

**Comment by borusyak** [comment]
Great!
