### ISSUE TITLE
LP-DID and Type Mismatch Error

### ISSUE THREAD

**Issue by grigoryaleksin** [borusyak/did_imputation#17]
Dear Kirill,

This hopefully is a simple question caused by my misunderstanding of how STATA works, but why does event_plot throw back a "r(109) type mismatch error" for arbitrary coefficient vectors? 

The reason I ask is that I have tried to plot some results created by the Linear Projection DID estimator (lpdid). The command stores results in a matrix e(results) from which I obtain a vector of coefficients using, for example, matrix coef= e(results)[1...,"coefficient"]. However, when trying to plot these as event_plot coef#, default_look stub_lag(tau#) stub_lead(pre#), the aforementioned problem emerges. 

I suspect it comes down to the specifics of how these vectors are created because the coefficient vectors of other estimators look pretty much the same. Any pointers would be very much appreciated!

Thanks again!

**Comment by borusyak** [comment]
Hi,
Please feel free to email me the minimum replication code & data to replicate your problem. 
While workarounds are usually possible to find, keep in mind that, to make other commands more easily compatible with event_plot, it's best to contact the authors of that package. Several people have successfully followed that strategy in the past.

Best,
Kirill
