### ISSUE TITLE
Additional Normalization 

### ISSUE THREAD

**Issue by lingerhsew** [borusyak/did_imputation#18]
Dear Borusyak,

I am doing an event study project and all the unites are treated. That is there are no never-treated unites. I want to include an additional normalization as recomended in one of your papers like τ−a = 0 in addition to τ−1 = 0. 

But I am not sure how I will impliment this in the did_imputation command. Could you please suggest how I will include the additional normalization?

**Comment by borusyak** [comment]
Hi,
You are reading the old (~2018) version of the paper. Please read the new one. Otherwise you don't need the command to impose any normalizations you like.

**Comment by lingerhsew** [comment]
Dear Borusyak,

Thanks a lot!
