### ISSUE TITLE
How to do PPML in this imputation based estimator

### ISSUE THREAD

**Issue by BashirMohammad** [borusyak/did_imputation#19]
Can we include model of Y(0) as a non-linear function such as poisson? I was thinking of this because I have to take logs but my outcome has many zeros as well. Is there an imputation based version of xtpoisson?
Thanks

**Comment by borusyak** [comment]
Hi,
Not with did_imputation but Jeff Wooldridge has a great paper about that.

**Comment by BashirMohammad** [comment]
Could you please refer me to that paper? Thank You

**Comment by borusyak** [comment]
I trust you to find it.
