### ISSUE TITLE
Error (430) can not convergency

### ISSUE THREAD

**Issue by xbrown1992** [borusyak/did_imputation#23]
Hello 
Than you for the amazing package in STATA. I am currently using this for my DID design. However, I ran into an error below.
Convergence of standard errors is not achieved for coefs: __w_tau0 __w_tau1 __w_tau2 __w_tau3 __w_tau4 __w_tau5 __w_tau6.
Try increasing the tolerance and the number of iterations, or use the nose option for the point estimates without SE.
convergence not achieved
r(430);
Any ideas about what is going on? I really appreciate any help you can provide.

**Comment by borusyak** [comment]
Hi,
Pleas read the error message; the helpfile discusses it, too.

**Comment by xbrown1992** [comment]
Thank you. I just found the help file.
One more question is left about the factor variable in the control list. 
I really want to include a few factor variable (such as i.education or i.father's education) in the control, is there a way to do that? I saw in the help file that if it's a dummy variable, it can be added to FE. But what if it includes more categories?

**Comment by borusyak** [comment]
Surely you can include a categorial variable into the FEs.
