### ISSUE TITLE
hetby option error: The hetby variable takes too many (over 30) values

### ISSUE THREAD

**Issue by SaiChrisZHANG** [borusyak/did_imputation#24]
Hi Kirill,

Thank you for the awesome package! I'm having a problem estimating treatment effect heterogeneity, I intend to use the hetby() option, but get the error: 
The hetby variable takes too many (over 30) values
too many categories
r(149);

When I use project() option, the estimation can be done. I was wondering if you have any insights on this error? The heterogeneity variable is a 0/1 dummy.

Also, Is there a way to plot the pre-treatment differences between the 2 groups for each period, like an event study for the heterogeneity?

Thank you in advance!

**Comment by borusyak** [comment]
Hi, 
Please check the number of unique values of the heterogeneity variable via "levelsof". If this doesn't solve the mystery, please email me the minimum working example of the problem.

**Comment by borusyak** [comment]
Regarding plotting, you can always do estimation separately by group and combine the graphs.
