### ISSUE TITLE
Is the chi-squared statistic or F-statistic returned when using pretrends?

### ISSUE THREAD

**Issue by duncanhobbs** [borusyak/did_imputation#3]
Dear Kirill,

Thanks for making this nice package.

In the [help](https://github.com/borusyak/did_imputation/blob/ae04aff4287c26a0be17f3dff9108bddd88237f0/did_imputation.sthlp#L167) file for this package it says that if pretrends is specified, the Wald statistic is returned as `e(pre_chi2)`.

When I look at the [ado](https://github.com/borusyak/did_imputation/blob/ae04aff4287c26a0be17f3dff9108bddd88237f0/did_imputation.ado#L514) file, it looks like the F-statistic is returned as `r(F)`, but not `r(chi2)`.

The returned scalar is called `e(pre_F)`, not `e(pre_chi2)`. This may just be a small issue in the help file.

Best,
Duncan

**Comment by borusyak** [comment]
Dear Duncan,
Thanks, well spotted! I'll fix this in the next release.

Best,
Kirill
