### ISSUE TITLE
Possible to bin endpoints after estimation?

### ISSUE THREAD

**Issue by duncanhobbs** [borusyak/did_imputation#4]
Hi Kirill,

Is it possible to bin the endpoints after estimation?

Or is that not a good idea because of the problems with binning that are outlined in your paper?

In a project I am working on I have made some regular and "stacked" event studies using OLS and I have binned endpoints for those.

Would a rough way to do this be just to plot the pretrends and horizons for the periods I am looking to display instead of plotting all horizons?

**Comment by borusyak** [comment]
Hi Duncan,
For the causal effects, once estimation is done with our method, you can average the estimates in whatever way you like. There is no binning option in the command but you can get the binned estimate via the wtr option. Of course, instead of binning you can just show a subset of coefs, but that's wouldn't be a good analogy.

For the pre-trends, I'm not sure what you are trying to bin. Perhaps it may be useful for you to take a look at our section 4.4 on pre-trend testing. Note that the reference group is different from what you may be used to.

Best,
Kirill

**Comment by duncanhobbs** [comment]
Thanks.

What I meant was if I am only interested in the relative period [-4, 4], and bin the distant periods < -4 and > 4 to -4 and 4, respectively.

Also in event studies estimated by OLS you have a base period (say t = -1) that is set to 0 at all of the effects are normalized relative to the base period.

But here the estimated treatment effects are based on imputed values for the control units so they are not measured relative to a base period but are the weighted average of the difference between the treated units and the imputed. 

Just trying to make sure I understand how this works relative to the standard estimator.

**Comment by borusyak** [comment]
Yes, exactly. So you can "bin" the post-coefficients in any way you like, you the distant pre-periods (e.g. before -4) are your reference group for the pre-trend test.

**Comment by duncanhobbs** [comment]
Thanks.

If I understand correctly if no `wtr` is specified, then the default is just to use the share of observations corresponding to each horizon.  

So if I wanted to bin all posttreatment periods larger than 4 could I do something like this?

```
gen K = t - Ei

count if K == 0
gen wtrzero = (K== 0)/r(N)

count if K == 1
gen wtrpos1 = (K==1)/r(N)

count if K == 2
gen wtrpos2 = (K==2)/r(N)

count if K == 3
gen wtrpos3 = (K==3)/r(N)

count if K>= 4
gen wtrbin (K>=4 & !missing(K))/r(N)

did_imputation Y i t Ei, allhorizons wtr(wtr_bin)
```
Or should I only get the horizons from 0/4 like the following?

`did_imputation Y i t Ei, horizons(0/4) wtr(wtr_bin)`

It looks like only including horizons 0/4 drops observations where the time relative to treatment is greater than 4 but the estimated coefficients and standard errors for horizons 0/4 don't change whether `horizons(0/4)` or `allhorizons` is used.

**Comment by borusyak** [comment]
It should be something like this:
did_imputation Y i t Ei, wtr(wtrzero wtrpos1 wtrpos2 wtrpo3 wtr_bin)

Let me know if it doesn't work! (horizons() or allhorizons will split the wtr into different horizons---you don't want that)
