### ISSUE TITLE
Normalize coefficients relative to base period

### ISSUE THREAD

**Issue by duncanhobbs** [borusyak/did_imputation#5]
Hi Kirill,

I was wondering about normalizing the calculated regression coefficients relative to a base period.

Is there a problem with doing this?

If this is not advisable how should results using this estimator be compared to traditional event studies estimated using OLS? 

Thank you for helping me understand how to use this package.

**Comment by borusyak** [comment]
Hi Duncan,
Yes, we view this as a bad practice: one is interested in causal effects of the treatment and estimates them by imposing certain assumptions. There is no such thing as "casual effect relative to some period". Please read the paper for more details.
