### ISSUE TITLE
Potential bias by singletons

### ISSUE THREAD

**Issue by Irazall** [borusyak/did_imputation#9]
Dear authors, thank you for this great package!
I have a question concerning singletons: When I run the `did_imputation` command and add the option `verbose` I see a warning stating 
```
WARNING: Singleton observations not dropped; statistical significance is biased (link)
```
The link leads to the[ this page](http://scorreia.com/research/singletons.pdf) stating that there might be problems with singletons that in the end overestimate statistical significance. Hence, `reghdfe` now automatically drops these observations. So my question is, why does `did_imputation` keep them? Isn't this a potential source of bias? Is there an option to drop these singletons? Or is this no problem at all?

Thank you in advance!

**Comment by borusyak** [comment]
Hi,
No, do not worry about this. The singletons are kept for technical reasons at an intermediate step.

Best,
Kirill
